In [1]:
import pandas as pd
import numpy as np

In [2]:
credit_spread = pd.read_excel('./data_files/Credit_spreads.xlsx')
print(credit_spread)

    Unnamed: 0  CH1206367588  CH0508785711  CH1148728210  CH1191714703  \
0   2014-12-31           NaN           NaN           NaN           NaN
1   2015-01-31           NaN           NaN           NaN           NaN
2   2015-02-28           NaN           NaN           NaN           NaN
3   2015-03-31           NaN           NaN           NaN           NaN
4   2015-04-30           NaN           NaN           NaN           NaN
..         ...           ...           ...           ...           ...
119 2024-11-30     40.648698     45.705244     46.888150     31.703593
120 2024-12-31     37.884902     41.179714     37.778766     31.639926
121 2025-01-31     36.568834     36.496609     39.099846     31.868368
122 2025-02-28     35.622504     36.393082     37.721346     25.701737
123 2025-03-31     38.077652     39.232499     43.311156     35.678804

     CH0354836113  CH1194355116  CH0553331890  CH0347556901  CH0147144361  \
0             NaN           NaN           NaN           NaN     40.023726
1             NaN           NaN           NaN           NaN     33.703669
2             NaN           NaN           NaN           NaN     39.279573
3             NaN           NaN           NaN           NaN     39.506407
4             NaN           NaN           NaN           NaN     36.903359
..            ...           ...           ...           ...           ...
119     65.671164     46.652784     87.197168    -35.941549     34.595856
120     52.083323     45.991133     83.985968     -1.787884     29.897599
121     55.489867     45.942024     83.428336     -2.072222     28.304682
122     65.502891     45.304060     82.311511    -10.576515     23.608455
123     58.396393     46.515541     90.336183      6.475989     26.290042

     ...  CH0551990689  CH1101096522  CH1118223424  CH0537261932  \
0    ...           NaN           NaN           NaN           NaN
1    ...           NaN           NaN           NaN           NaN
2    ...           NaN           NaN           NaN           NaN
3    ...           NaN           NaN           NaN           NaN
4    ...           NaN           NaN           NaN           NaN
..   ...           ...           ...           ...           ...
119  ...    -25.528675     34.167202     51.140641     45.485864
120  ...     13.422562     31.188644     43.295273     51.838123
121  ...     16.749537     30.226329     39.894109     50.598290
122  ...     14.854844     23.137477     40.704511     51.229554
123  ...     45.514929     29.674092     42.690792     58.816928

     CH0373476339  CH0576402165  CH0572327002  CH0435590358  CH0433761308  \
0             NaN           NaN           NaN           NaN           NaN
1             NaN           NaN           NaN           NaN           NaN
2             NaN           NaN           NaN           NaN           NaN
3             NaN           NaN           NaN           NaN           NaN
4             NaN           NaN           NaN           NaN           NaN
..            ...           ...           ...           ...           ...
119     39.544954     73.036573     41.096632     57.500753    -45.537216
120     35.069835     75.791337     47.735739     12.215654    -11.464241
121     33.676932     92.362287     44.336784     17.783298     -2.750309
122     29.972325     71.895647     44.055470     15.425463     -5.942367
123     33.528310     82.660422     50.572633     37.873156     14.276602

     CH0344583817
0             NaN
1             NaN
2             NaN
3             NaN
4             NaN
..            ...
119     35.936337
120     34.912784
121     32.883224
122     29.074698
123     34.453601

[124 rows x 530 columns]

In [3]:
credit_spread.iloc[:, 1:] =  credit_spread.iloc[:, 1:] / 10000

In [4]:
print(credit_spread)

    Unnamed: 0  CH1206367588  CH0508785711  CH1148728210  CH1191714703  \
0   2014-12-31           NaN           NaN           NaN           NaN
1   2015-01-31           NaN           NaN           NaN           NaN
2   2015-02-28           NaN           NaN           NaN           NaN
3   2015-03-31           NaN           NaN           NaN           NaN
4   2015-04-30           NaN           NaN           NaN           NaN
..         ...           ...           ...           ...           ...
119 2024-11-30      0.004065      0.004571      0.004689      0.003170
120 2024-12-31      0.003788      0.004118      0.003778      0.003164
121 2025-01-31      0.003657      0.003650      0.003910      0.003187
122 2025-02-28      0.003562      0.003639      0.003772      0.002570
123 2025-03-31      0.003808      0.003923      0.004331      0.003568

     CH0354836113  CH1194355116  CH0553331890  CH0347556901  CH0147144361  \
0             NaN           NaN           NaN           NaN      0.004002
1             NaN           NaN           NaN           NaN      0.003370
2             NaN           NaN           NaN           NaN      0.003928
3             NaN           NaN           NaN           NaN      0.003951
4             NaN           NaN           NaN           NaN      0.003690
..            ...           ...           ...           ...           ...
119      0.006567      0.004665      0.008720     -0.003594      0.003460
120      0.005208      0.004599      0.008399     -0.000179      0.002990
121      0.005549      0.004594      0.008343     -0.000207      0.002830
122      0.006550      0.004530      0.008231     -0.001058      0.002361
123      0.005840      0.004652      0.009034      0.000648      0.002629

     ...  CH0551990689  CH1101096522  CH1118223424  CH0537261932  \
0    ...           NaN           NaN           NaN           NaN
1    ...           NaN           NaN           NaN           NaN
2    ...           NaN           NaN           NaN           NaN
3    ...           NaN           NaN           NaN           NaN
4    ...           NaN           NaN           NaN           NaN
..   ...           ...           ...           ...           ...
119  ...     -0.002553      0.003417      0.005114      0.004549
120  ...      0.001342      0.003119      0.004330      0.005184
121  ...      0.001675      0.003023      0.003989      0.005060
122  ...      0.001485      0.002314      0.004070      0.005123
123  ...      0.004551      0.002967      0.004269      0.005882

     CH0373476339  CH0576402165  CH0572327002  CH0435590358  CH0433761308  \
0             NaN           NaN           NaN           NaN           NaN
1             NaN           NaN           NaN           NaN           NaN
2             NaN           NaN           NaN           NaN           NaN
3             NaN           NaN           NaN           NaN           NaN
4             NaN           NaN           NaN           NaN           NaN
..            ...           ...           ...           ...           ...
119      0.003954      0.007304      0.004110      0.005750     -0.004554
120      0.003507      0.007579      0.004774      0.001222     -0.001146
121      0.003368      0.009236      0.004434      0.001778     -0.000275
122      0.002997      0.007190      0.004406      0.001543     -0.000594
123      0.003353      0.008266      0.005057      0.003787      0.001428

     CH0344583817
0             NaN
1             NaN
2             NaN
3             NaN
4             NaN
..            ...
119      0.003594
120      0.003491
121      0.003288
122      0.002907
123      0.003445

[124 rows x 530 columns]

In [5]:
print(credit_spread)

    Unnamed: 0  CH1206367588  CH0508785711  CH1148728210  CH1191714703  \
0   2014-12-31           NaN           NaN           NaN           NaN
1   2015-01-31           NaN           NaN           NaN           NaN
2   2015-02-28           NaN           NaN           NaN           NaN
3   2015-03-31           NaN           NaN           NaN           NaN
4   2015-04-30           NaN           NaN           NaN           NaN
..         ...           ...           ...           ...           ...
119 2024-11-30      0.004065      0.004571      0.004689      0.003170
120 2024-12-31      0.003788      0.004118      0.003778      0.003164
121 2025-01-31      0.003657      0.003650      0.003910      0.003187
122 2025-02-28      0.003562      0.003639      0.003772      0.002570
123 2025-03-31      0.003808      0.003923      0.004331      0.003568

     CH0354836113  CH1194355116  CH0553331890  CH0347556901  CH0147144361  \
0             NaN           NaN           NaN           NaN      0.004002
1             NaN           NaN           NaN           NaN      0.003370
2             NaN           NaN           NaN           NaN      0.003928
3             NaN           NaN           NaN           NaN      0.003951
4             NaN           NaN           NaN           NaN      0.003690
..            ...           ...           ...           ...           ...
119      0.006567      0.004665      0.008720     -0.003594      0.003460
120      0.005208      0.004599      0.008399     -0.000179      0.002990
121      0.005549      0.004594      0.008343     -0.000207      0.002830
122      0.006550      0.004530      0.008231     -0.001058      0.002361
123      0.005840      0.004652      0.009034      0.000648      0.002629

     ...  CH0551990689  CH1101096522  CH1118223424  CH0537261932  \
0    ...           NaN           NaN           NaN           NaN
1    ...           NaN           NaN           NaN           NaN
2    ...           NaN           NaN           NaN           NaN
3    ...           NaN           NaN           NaN           NaN
4    ...           NaN           NaN           NaN           NaN
..   ...           ...           ...           ...           ...
119  ...     -0.002553      0.003417      0.005114      0.004549
120  ...      0.001342      0.003119      0.004330      0.005184
121  ...      0.001675      0.003023      0.003989      0.005060
122  ...      0.001485      0.002314      0.004070      0.005123
123  ...      0.004551      0.002967      0.004269      0.005882

     CH0373476339  CH0576402165  CH0572327002  CH0435590358  CH0433761308  \
0             NaN           NaN           NaN           NaN           NaN
1             NaN           NaN           NaN           NaN           NaN
2             NaN           NaN           NaN           NaN           NaN
3             NaN           NaN           NaN           NaN           NaN
4             NaN           NaN           NaN           NaN           NaN
..            ...           ...           ...           ...           ...
119      0.003954      0.007304      0.004110      0.005750     -0.004554
120      0.003507      0.007579      0.004774      0.001222     -0.001146
121      0.003368      0.009236      0.004434      0.001778     -0.000275
122      0.002997      0.007190      0.004406      0.001543     -0.000594
123      0.003353      0.008266      0.005057      0.003787      0.001428

     CH0344583817
0             NaN
1             NaN
2             NaN
3             NaN
4             NaN
..            ...
119      0.003594
120      0.003491
121      0.003288
122      0.002907
123      0.003445

[124 rows x 530 columns]

In [6]:
credit_spread=credit_spread.rename(columns={"Unnamed: 0":"Date"})

In [7]:
print(credit_spread.tail())

          Date  CH1206367588  CH0508785711  CH1148728210  CH1191714703  \
119 2024-11-30      0.004065      0.004571      0.004689      0.003170
120 2024-12-31      0.003788      0.004118      0.003778      0.003164
121 2025-01-31      0.003657      0.003650      0.003910      0.003187
122 2025-02-28      0.003562      0.003639      0.003772      0.002570
123 2025-03-31      0.003808      0.003923      0.004331      0.003568

     CH0354836113  CH1194355116  CH0553331890  CH0347556901  CH0147144361  \
119      0.006567      0.004665      0.008720     -0.003594      0.003460
120      0.005208      0.004599      0.008399     -0.000179      0.002990
121      0.005549      0.004594      0.008343     -0.000207      0.002830
122      0.006550      0.004530      0.008231     -0.001058      0.002361
123      0.005840      0.004652      0.009034      0.000648      0.002629

     ...  CH0551990689  CH1101096522  CH1118223424  CH0537261932  \
119  ...     -0.002553      0.003417      0.005114      0.004549
120  ...      0.001342      0.003119      0.004330      0.005184
121  ...      0.001675      0.003023      0.003989      0.005060
122  ...      0.001485      0.002314      0.004070      0.005123
123  ...      0.004551      0.002967      0.004269      0.005882

     CH0373476339  CH0576402165  CH0572327002  CH0435590358  CH0433761308  \
119      0.003954      0.007304      0.004110      0.005750     -0.004554
120      0.003507      0.007579      0.004774      0.001222     -0.001146
121      0.003368      0.009236      0.004434      0.001778     -0.000275
122      0.002997      0.007190      0.004406      0.001543     -0.000594
123      0.003353      0.008266      0.005057      0.003787      0.001428

     CH0344583817
119      0.003594
120      0.003491
121      0.003288
122      0.002907
123      0.003445

[5 rows x 530 columns]

In [8]:
credit_spread_diff= credit_spread.drop(columns='Date').diff()
print(credit_spread_diff)

     CH1206367588  CH0508785711  CH1148728210  CH1191714703  CH0354836113  \
0             NaN           NaN           NaN           NaN           NaN
1             NaN           NaN           NaN           NaN           NaN
2             NaN           NaN           NaN           NaN           NaN
3             NaN           NaN           NaN           NaN           NaN
4             NaN           NaN           NaN           NaN           NaN
..            ...           ...           ...           ...           ...
119      0.000144 -9.849883e-07      0.000121     -0.000255      0.000308
120     -0.000276 -4.525530e-04     -0.000911     -0.000006     -0.001359
121     -0.000132 -4.683105e-04      0.000132      0.000023      0.000341
122     -0.000095 -1.035270e-05     -0.000138     -0.000617      0.001001
123      0.000246  2.839416e-04      0.000559      0.000998     -0.000711

     CH1194355116  CH0553331890  CH0347556901  CH0147144361  CH1189217834  \
0             NaN           NaN           NaN           NaN           NaN
1             NaN           NaN           NaN     -0.000632           NaN
2             NaN           NaN           NaN      0.000558           NaN
3             NaN           NaN           NaN      0.000023           NaN
4             NaN           NaN           NaN     -0.000260           NaN
..            ...           ...           ...           ...           ...
119     -0.000206      0.000043     -0.001432      0.000072      0.000051
120     -0.000066     -0.000321      0.003415     -0.000470     -0.000468
121     -0.000005     -0.000056     -0.000028     -0.000159     -0.000290
122     -0.000064     -0.000112     -0.000850     -0.000470      0.000050
123      0.000121      0.000802      0.001705      0.000268      0.000203

     ...  CH0551990689  CH1101096522  CH1118223424  CH0537261932  \
0    ...           NaN           NaN           NaN           NaN
1    ...           NaN           NaN           NaN           NaN
2    ...           NaN           NaN           NaN           NaN
3    ...           NaN           NaN           NaN           NaN
4    ...           NaN           NaN           NaN           NaN
..   ...           ...           ...           ...           ...
119  ...     -0.008454     -0.000013      0.000429     -0.000312
120  ...      0.003895     -0.000298     -0.000785      0.000635
121  ...      0.000333     -0.000096     -0.000340     -0.000124
122  ...     -0.000189     -0.000709      0.000081      0.000063
123  ...      0.003066      0.000654      0.000199      0.000759

     CH0373476339  CH0576402165  CH0572327002  CH0435590358  CH0433761308  \
0             NaN           NaN           NaN           NaN           NaN
1             NaN           NaN           NaN           NaN           NaN
2             NaN           NaN           NaN           NaN           NaN
3             NaN           NaN           NaN           NaN           NaN
4             NaN           NaN           NaN           NaN           NaN
..            ...           ...           ...           ...           ...
119      0.000254     -0.001076     -0.000538      0.000497     -0.001872
120     -0.000448      0.000275      0.000664     -0.004529      0.003407
121     -0.000139      0.001657     -0.000340      0.000557      0.000871
122     -0.000370     -0.002047     -0.000028     -0.000236     -0.000319
123      0.000356      0.001076      0.000652      0.002245      0.002022

     CH0344583817
0             NaN
1             NaN
2             NaN
3             NaN
4             NaN
..            ...
119     -0.000106
120     -0.000102
121     -0.000203
122     -0.000381
123      0.000538

[124 rows x 529 columns]

In [9]:
credit_spread_diff['Date'] = credit_spread['Date']
print(credit_spread_diff.tail())

     CH1206367588  CH0508785711  CH1148728210  CH1191714703  CH0354836113  \
119      0.000144 -9.849883e-07      0.000121     -0.000255      0.000308
120     -0.000276 -4.525530e-04     -0.000911     -0.000006     -0.001359
121     -0.000132 -4.683105e-04      0.000132      0.000023      0.000341
122     -0.000095 -1.035270e-05     -0.000138     -0.000617      0.001001
123      0.000246  2.839416e-04      0.000559      0.000998     -0.000711

     CH1194355116  CH0553331890  CH0347556901  CH0147144361  CH1189217834  \
119     -0.000206      0.000043     -0.001432      0.000072      0.000051
120     -0.000066     -0.000321      0.003415     -0.000470     -0.000468
121     -0.000005     -0.000056     -0.000028     -0.000159     -0.000290
122     -0.000064     -0.000112     -0.000850     -0.000470      0.000050
123      0.000121      0.000802      0.001705      0.000268      0.000203

     ...  CH1101096522  CH1118223424  CH0537261932  CH0373476339  \
119  ...     -0.000013      0.000429     -0.000312      0.000254
120  ...     -0.000298     -0.000785      0.000635     -0.000448
121  ...     -0.000096     -0.000340     -0.000124     -0.000139
122  ...     -0.000709      0.000081      0.000063     -0.000370
123  ...      0.000654      0.000199      0.000759      0.000356

     CH0576402165  CH0572327002  CH0435590358  CH0433761308  CH0344583817  \
119     -0.001076     -0.000538      0.000497     -0.001872     -0.000106
120      0.000275      0.000664     -0.004529      0.003407     -0.000102
121      0.001657     -0.000340      0.000557      0.000871     -0.000203
122     -0.002047     -0.000028     -0.000236     -0.000319     -0.000381
123      0.001076      0.000652      0.002245      0.002022      0.000538

          Date
119 2024-11-30
120 2024-12-31
121 2025-01-31
122 2025-02-28
123 2025-03-31

[5 rows x 530 columns]

In [10]:
credit_spread_diff = credit_spread_diff[['Date'] + [col for col in credit_spread_diff.columns if col != 'Date']]

In [11]:
credit_spread_diff = round(credit_spread_diff, 5)
print(credit_spread_diff)

          Date  CH1206367588  CH0508785711  CH1148728210  CH1191714703  \
0   2014-12-31           NaN           NaN           NaN           NaN
1   2015-01-31           NaN           NaN           NaN           NaN
2   2015-02-28           NaN           NaN           NaN           NaN
3   2015-03-31           NaN           NaN           NaN           NaN
4   2015-04-30           NaN           NaN           NaN           NaN
..         ...           ...           ...           ...           ...
119 2024-11-30       0.00014      -0.00000       0.00012      -0.00025
120 2024-12-31      -0.00028      -0.00045      -0.00091      -0.00001
121 2025-01-31      -0.00013      -0.00047       0.00013       0.00002
122 2025-02-28      -0.00009      -0.00001      -0.00014      -0.00062
123 2025-03-31       0.00025       0.00028       0.00056       0.00100

     CH0354836113  CH1194355116  CH0553331890  CH0347556901  CH0147144361  \
0             NaN           NaN           NaN           NaN           NaN
1             NaN           NaN           NaN           NaN      -0.00063
2             NaN           NaN           NaN           NaN       0.00056
3             NaN           NaN           NaN           NaN       0.00002
4             NaN           NaN           NaN           NaN      -0.00026
..            ...           ...           ...           ...           ...
119       0.00031      -0.00021       0.00004      -0.00143       0.00007
120      -0.00136      -0.00007      -0.00032       0.00342      -0.00047
121       0.00034      -0.00000      -0.00006      -0.00003      -0.00016
122       0.00100      -0.00006      -0.00011      -0.00085      -0.00047
123      -0.00071       0.00012       0.00080       0.00171       0.00027

     ...  CH0551990689  CH1101096522  CH1118223424  CH0537261932  \
0    ...           NaN           NaN           NaN           NaN
1    ...           NaN           NaN           NaN           NaN
2    ...           NaN           NaN           NaN           NaN
3    ...           NaN           NaN           NaN           NaN
4    ...           NaN           NaN           NaN           NaN
..   ...           ...           ...           ...           ...
119  ...      -0.00845      -0.00001       0.00043      -0.00031
120  ...       0.00390      -0.00030      -0.00078       0.00064
121  ...       0.00033      -0.00010      -0.00034      -0.00012
122  ...      -0.00019      -0.00071       0.00008       0.00006
123  ...       0.00307       0.00065       0.00020       0.00076

     CH0373476339  CH0576402165  CH0572327002  CH0435590358  CH0433761308  \
0             NaN           NaN           NaN           NaN           NaN
1             NaN           NaN           NaN           NaN           NaN
2             NaN           NaN           NaN           NaN           NaN
3             NaN           NaN           NaN           NaN           NaN
4             NaN           NaN           NaN           NaN           NaN
..            ...           ...           ...           ...           ...
119       0.00025      -0.00108      -0.00054       0.00050      -0.00187
120      -0.00045       0.00028       0.00066      -0.00453       0.00341
121      -0.00014       0.00166      -0.00034       0.00056       0.00087
122      -0.00037      -0.00205      -0.00003      -0.00024      -0.00032
123       0.00036       0.00108       0.00065       0.00224       0.00202

     CH0344583817
0             NaN
1             NaN
2             NaN
3             NaN
4             NaN
..            ...
119      -0.00011
120      -0.00010
121      -0.00020
122      -0.00038
123       0.00054

[124 rows x 530 columns]

In [12]:
credit_spread_diff = credit_spread_diff.drop([0,121,122,123])
print(credit_spread_diff)

          Date  CH1206367588  CH0508785711  CH1148728210  CH1191714703  \
1   2015-01-31           NaN           NaN           NaN           NaN
2   2015-02-28           NaN           NaN           NaN           NaN
3   2015-03-31           NaN           NaN           NaN           NaN
4   2015-04-30           NaN           NaN           NaN           NaN
5   2015-05-31           NaN           NaN           NaN           NaN
..         ...           ...           ...           ...           ...
116 2024-08-31      -0.00058      -0.00068       0.00053       0.00000
117 2024-09-30      -0.00013       0.00002       0.00033      -0.00014
118 2024-10-31      -0.00033      -0.00014      -0.00047       0.00005
119 2024-11-30       0.00014      -0.00000       0.00012      -0.00025
120 2024-12-31      -0.00028      -0.00045      -0.00091      -0.00001

     CH0354836113  CH1194355116  CH0553331890  CH0347556901  CH0147144361  \
1             NaN           NaN           NaN           NaN      -0.00063
2             NaN           NaN           NaN           NaN       0.00056
3             NaN           NaN           NaN           NaN       0.00002
4             NaN           NaN           NaN           NaN      -0.00026
5             NaN           NaN           NaN           NaN       0.00119
..            ...           ...           ...           ...           ...
116      -0.00028      -0.00083       0.00016      -0.00478      -0.00025
117       0.00022      -0.00003       0.00011       0.00193       0.00008
118      -0.00029       0.00009      -0.00078      -0.00093      -0.00035
119       0.00031      -0.00021       0.00004      -0.00143       0.00007
120      -0.00136      -0.00007      -0.00032       0.00342      -0.00047

     ...  CH0551990689  CH1101096522  CH1118223424  CH0537261932  \
1    ...           NaN           NaN           NaN           NaN
2    ...           NaN           NaN           NaN           NaN
3    ...           NaN           NaN           NaN           NaN
4    ...           NaN           NaN           NaN           NaN
5    ...           NaN           NaN           NaN           NaN
..   ...           ...           ...           ...           ...
116  ...       0.00188      -0.00027      -0.00062      -0.00055
117  ...       0.00056       0.00019      -0.00001      -0.00063
118  ...       0.00001      -0.00037      -0.00016      -0.00022
119  ...      -0.00845      -0.00001       0.00043      -0.00031
120  ...       0.00390      -0.00030      -0.00078       0.00064

     CH0373476339  CH0576402165  CH0572327002  CH0435590358  CH0433761308  \
1             NaN           NaN           NaN           NaN           NaN
2             NaN           NaN           NaN           NaN           NaN
3             NaN           NaN           NaN           NaN           NaN
4             NaN           NaN           NaN           NaN           NaN
5             NaN           NaN           NaN           NaN           NaN
..            ...           ...           ...           ...           ...
116      -0.00035      -0.00052      -0.00054       0.00191       0.00158
117      -0.00004       0.00193      -0.00040       0.00050       0.00052
118      -0.00036      -0.00303      -0.00031      -0.00001      -0.00631
119       0.00025      -0.00108      -0.00054       0.00050      -0.00187
120      -0.00045       0.00028       0.00066      -0.00453       0.00341

     CH0344583817
1             NaN
2             NaN
3             NaN
4             NaN
5             NaN
..            ...
116       0.00001
117       0.00016
118      -0.00030
119      -0.00011
120      -0.00010

[120 rows x 530 columns]

In [13]:
credit_spread_diff_long = credit_spread_diff.melt(id_vars="Date", value_vars=credit_spread_diff[1:529], var_name="ISIN", value_name="CS_Change")
print(credit_spread_diff_long)

            Date          ISIN  CS_Change
0     2015-01-31  CH1206367588        NaN
1     2015-02-28  CH1206367588        NaN
2     2015-03-31  CH1206367588        NaN
3     2015-04-30  CH1206367588        NaN
4     2015-05-31  CH1206367588        NaN
...          ...           ...        ...
63475 2024-08-31  CH0344583817    0.00001
63476 2024-09-30  CH0344583817    0.00016
63477 2024-10-31  CH0344583817   -0.00030
63478 2024-11-30  CH0344583817   -0.00011
63479 2024-12-31  CH0344583817   -0.00010

[63480 rows x 3 columns]

In [14]:
#We read factors
four_factors = pd.read_excel('./data_files/four_factors.xlsx')
print(four_factors)

          Date  change_in_10Y_bond  change_in_slope  SMI_return  V3X_change
0   2015-01-31            -0.00395          0.00006   -0.068915    0.045699
1   2015-02-28             0.00082          0.00186    0.072378   -0.076882
2   2015-03-31            -0.00058         -0.00049    0.012616    0.023650
3   2015-04-30             0.00077          0.00064   -0.005696    0.011979
4   2015-05-31            -0.00090          0.00010    0.017546   -0.020550
..         ...                 ...              ...         ...         ...
115 2024-08-31             0.00007          0.00104    0.009627    0.012917
116 2024-09-30            -0.00054          0.00076   -0.021762   -0.001398
117 2024-10-31             0.00007          0.00050   -0.031382    0.035715
118 2024-11-30            -0.00177          0.00034   -0.002438   -0.042992
119 2024-12-31             0.00075          0.00168   -0.013979    0.002462

[120 rows x 5 columns]

In [15]:
# we convert other factors into data frames
change_in_LR = pd.read_excel('./data_files/delta_LR.xlsx')
print(change_in_LR.head())

        Date  CH506071106  CH0419041436  CH0444153792  CH0184636915  \
0 2015-01-31      0.11052       0.11052       0.11052       0.11052
1 2015-02-28      0.11052       0.11052       0.11052       0.11052
2 2015-03-31      0.11052       0.11052       0.11052       0.11052
3 2015-04-30      0.11052       0.11052       0.11052       0.11052
4 2015-05-31      0.11052       0.11052       0.11052       0.11052

   CH0301832561  CH0379354225  CH0262085076  CH0522158945  CH0506071288  ...  \
0       0.11052       0.11052       0.11052       0.11052       0.11052  ...
1       0.11052       0.11052       0.11052       0.11052       0.11052  ...
2       0.11052       0.11052       0.11052       0.11052       0.11052  ...
3       0.11052       0.11052       0.11052       0.11052       0.11052  ...
4       0.11052       0.11052       0.11052       0.11052       0.11052  ...

   CH1170565621  CH0120408122  CH0130158642  CH0347082783  CH0116306868  \
0      0.126603      0.126603      0.126603      0.126603      0.126603
1      0.126603      0.126603      0.126603      0.126603      0.126603
2      0.126603      0.126603      0.126603      0.126603      0.126603
3      0.126603      0.126603      0.126603      0.126603      0.126603
4      0.126603      0.126603      0.126603      0.126603      0.126603

   CH1206367638  CH0119729793  CH0342587638  CH0373476339  CH0247611269
0      0.126603      0.126603      0.126603      0.126603      0.007086
1      0.126603      0.126603      0.126603      0.126603      0.007086
2      0.126603      0.126603      0.126603      0.126603      0.007086
3      0.126603      0.126603      0.126603      0.126603      0.007086
4      0.126603      0.126603      0.126603      0.126603      0.007086

[5 rows x 530 columns]

In [16]:
change_in_LR.iloc[:, 1:] =  change_in_LR.iloc[:, 1:] / 100
print(change_in_LR)

          Date  CH506071106  CH0419041436  CH0444153792  CH0184636915  \
0   2015-01-31     0.001105      0.001105      0.001105      0.001105
1   2015-02-28     0.001105      0.001105      0.001105      0.001105
2   2015-03-31     0.001105      0.001105      0.001105      0.001105
3   2015-04-30     0.001105      0.001105      0.001105      0.001105
4   2015-05-31     0.001105      0.001105      0.001105      0.001105
..         ...          ...           ...           ...           ...
115 2024-08-31     0.003347      0.003347      0.003347      0.003347
116 2024-09-30     0.003347      0.003347      0.003347      0.003347
117 2024-10-31     0.003347      0.003347      0.003347      0.003347
118 2024-11-30     0.003347      0.003347      0.003347      0.003347
119 2024-12-31     0.003347      0.003347      0.003347      0.003347

     CH0301832561  CH0379354225  CH0262085076  CH0522158945  CH0506071288  \
0        0.001105      0.001105      0.001105      0.001105      0.001105
1        0.001105      0.001105      0.001105      0.001105      0.001105
2        0.001105      0.001105      0.001105      0.001105      0.001105
3        0.001105      0.001105      0.001105      0.001105      0.001105
4        0.001105      0.001105      0.001105      0.001105      0.001105
..            ...           ...           ...           ...           ...
115      0.003347      0.003347      0.003347      0.003347      0.003347
116      0.003347      0.003347      0.003347      0.003347      0.003347
117      0.003347      0.003347      0.003347      0.003347      0.003347
118      0.003347      0.003347      0.003347      0.003347      0.003347
119      0.003347      0.003347      0.003347      0.003347      0.003347

     ...  CH1170565621  CH0120408122  CH0130158642  CH0347082783  \
0    ...      0.001266      0.001266      0.001266      0.001266
1    ...      0.001266      0.001266      0.001266      0.001266
2    ...      0.001266      0.001266      0.001266      0.001266
3    ...      0.001266      0.001266      0.001266      0.001266
4    ...      0.001266      0.001266      0.001266      0.001266
..   ...           ...           ...           ...           ...
115  ...     -0.000896     -0.000896     -0.000896     -0.000896
116  ...     -0.000896     -0.000896     -0.000896     -0.000896
117  ...     -0.000896     -0.000896     -0.000896     -0.000896
118  ...     -0.000896     -0.000896     -0.000896     -0.000896
119  ...     -0.000896     -0.000896     -0.000896     -0.000896

     CH0116306868  CH1206367638  CH0119729793  CH0342587638  CH0373476339  \
0        0.001266      0.001266      0.001266      0.001266      0.001266
1        0.001266      0.001266      0.001266      0.001266      0.001266
2        0.001266      0.001266      0.001266      0.001266      0.001266
3        0.001266      0.001266      0.001266      0.001266      0.001266
4        0.001266      0.001266      0.001266      0.001266      0.001266
..            ...           ...           ...           ...           ...
115     -0.000896     -0.000896     -0.000896     -0.000896     -0.000896
116     -0.000896     -0.000896     -0.000896     -0.000896     -0.000896
117     -0.000896     -0.000896     -0.000896     -0.000896     -0.000896
118     -0.000896     -0.000896     -0.000896     -0.000896     -0.000896
119     -0.000896     -0.000896     -0.000896     -0.000896     -0.000896

     CH0247611269
0        0.000071
1        0.000071
2        0.000071
3        0.000071
4        0.000071
..            ...
115      0.000000
116      0.000000
117      0.000000
118      0.000000
119      0.000000

[120 rows x 530 columns]

In [17]:
change_in_LR_long = change_in_LR.melt(id_vars="Date", value_vars=change_in_LR[1:529], var_name="ISIN", value_name='delta LR')
print(change_in_LR_long)

            Date          ISIN  delta LR
0     2015-01-31   CH506071106  0.001105
1     2015-02-28   CH506071106  0.001105
2     2015-03-31   CH506071106  0.001105
3     2015-04-30   CH506071106  0.001105
4     2015-05-31   CH506071106  0.001105
...          ...           ...       ...
63475 2024-08-31  CH0247611269  0.000000
63476 2024-09-30  CH0247611269  0.000000
63477 2024-10-31  CH0247611269  0.000000
63478 2024-11-30  CH0247611269  0.000000
63479 2024-12-31  CH0247611269  0.000000

[63480 rows x 3 columns]

In [18]:
#Try merging
working_df = credit_spread_diff_long.merge(change_in_LR_long, on=['Date', 'ISIN'], how="left")
print(working_df)

            Date          ISIN  CS_Change  delta LR
0     2015-01-31  CH1206367588        NaN  0.001782
1     2015-02-28  CH1206367588        NaN  0.001782
2     2015-03-31  CH1206367588        NaN  0.001782
3     2015-04-30  CH1206367588        NaN  0.001782
4     2015-05-31  CH1206367588        NaN  0.001782
...          ...           ...        ...       ...
63475 2024-08-31  CH0344583817    0.00001  0.000040
63476 2024-09-30  CH0344583817    0.00016  0.000040
63477 2024-10-31  CH0344583817   -0.00030  0.000040
63478 2024-11-30  CH0344583817   -0.00011  0.000040
63479 2024-12-31  CH0344583817   -0.00010  0.000040

[63480 rows x 4 columns]

In [19]:
working_df2 = working_df.merge(four_factors, on="Date", how="left")
print(working_df2.head())

        Date          ISIN  CS_Change  delta LR  change_in_10Y_bond  \
0 2015-01-31  CH1206367588        NaN  0.001782            -0.00395
1 2015-02-28  CH1206367588        NaN  0.001782             0.00082
2 2015-03-31  CH1206367588        NaN  0.001782            -0.00058
3 2015-04-30  CH1206367588        NaN  0.001782             0.00077
4 2015-05-31  CH1206367588        NaN  0.001782            -0.00090

   change_in_slope  SMI_return  V3X_change
0          0.00006   -0.068915    0.045699
1          0.00186    0.072378   -0.076882
2         -0.00049    0.012616    0.023650
3          0.00064   -0.005696    0.011979
4          0.00010    0.017546   -0.020550

In [20]:
working_df2['ISIN'] = pd.factorize(working_df2['ISIN'])[0]

In [21]:
print(working_df2.columns.to_list())

['Date', 'ISIN', 'CS_Change', 'delta LR', 'change_in_10Y_bond', 'change_in_slope', 'SMI_return', 'V3X_change']

In [22]:
working_df2.columns = working_df2.columns.str.strip().str.lower()

print(working_df2.columns.to_list())

['date', 'isin', 'cs_change', 'delta lr', 'change_in_10y_bond', 'change_in_slope', 'smi_return', 'v3x_change']

In [23]:
working_df2['isin'].dtype

dtype('int64')

## Regression

In [24]:
#we check how many empty values we have
print(working_df2.isna().sum())

date                      0
isin                      0
cs_change             27201
delta lr                120
change_in_10y_bond        0
change_in_slope           0
smi_return                0
v3x_change                0
dtype: int64

In [25]:
#we drop empty values
working_df_clean = working_df2.dropna()
print(working_df_clean.head())

         date  isin  cs_change  delta lr  change_in_10y_bond  change_in_slope  \
94 2022-11-30     0   -0.00267  0.000058            -0.00028         -0.00395
95 2022-12-31     0   -0.00102  0.000058             0.00517          0.00171
96 2023-01-31     0   -0.00020  0.000024            -0.00310         -0.00158
97 2023-02-28     0    0.00077  0.000024             0.00167         -0.00069
98 2023-03-31     0    0.00259  0.000024            -0.00229         -0.00179

    smi_return  v3x_change
94    0.027314   -0.030361
95   -0.036456   -0.005036
96    0.050557    0.005429
97   -0.016747   -0.001126
98    0.000710   -0.016202

In [26]:
print(working_df_clean.isna().sum())

date                  0
isin                  0
cs_change             0
delta lr              0
change_in_10y_bond    0
change_in_slope       0
smi_return            0
v3x_change            0
dtype: int64

In [27]:
#We add credit rating and maturity
credit_rating = pd.read_excel("./data_files/credit_rating.xlsx")
bond_maturity = pd.read_excel("./data_files/maturities.xlsx")
print(bond_maturity.head())
print(credit_rating.head())

           isin  maturity
0  CH0506071106      10.0
1  CH0419041436      10.0
2  CH0444153792       9.0
3  CH0184636915      25.0
4  CH0301832561      10.0
           isin rating
0  CH0506071106   AAA
1  CH0419041436   AAA
2  CH0444153792   AAA
3  CH0184636915   AAA
4  CH0301832561   AAA

In [28]:
rating_and_maturity = credit_rating.merge(bond_maturity, on='isin', how='left')
print(rating_and_maturity)

             isin rating  maturity
0    CH0506071106   AAA       10.0
1    CH0419041436   AAA       10.0
2    CH0444153792   AAA        9.0
3    CH0184636915   AAA       25.0
4    CH0301832561   AAA       10.0
..            ...    ...       ...
524  CH1206367638    AAA       5.0
525  CH0119729793    AAA      24.0
526  CH0342587638    AAA      10.0
527  CH0373476339    AAA      10.0
528  CH0247611269     AA      12.0

[529 rows x 3 columns]

In [29]:
rating_and_maturity['isin'] = pd.factorize(rating_and_maturity['isin'])[0]

In [30]:
working_df_clean = working_df_clean.merge(rating_and_maturity, on='isin',how='left')
print(working_df_clean.head())

        date  isin  cs_change  delta lr  change_in_10y_bond  change_in_slope  \
0 2022-11-30     0   -0.00267  0.000058            -0.00028         -0.00395
1 2022-12-31     0   -0.00102  0.000058             0.00517          0.00171
2 2023-01-31     0   -0.00020  0.000024            -0.00310         -0.00158
3 2023-02-28     0    0.00077  0.000024             0.00167         -0.00069
4 2023-03-31     0    0.00259  0.000024            -0.00229         -0.00179

   smi_return  v3x_change rating  maturity
0    0.027314   -0.030361   AAA       10.0
1   -0.036456   -0.005036   AAA       10.0
2    0.050557    0.005429   AAA       10.0
3   -0.016747   -0.001126   AAA       10.0
4    0.000710   -0.016202   AAA       10.0

In [31]:
#We read macro factors
macro_factors = pd.read_excel("./data_files/macroFactors.xlsx")
print(macro_factors)

          date  cpi_change  unempl_change  gdp_change
0   2015-01-31     -0.4006           0.30    0.131167
1   2015-02-28     -0.2571           0.10    0.131167
2   2015-03-31      0.3255          -0.10    0.131167
3   2015-04-30     -0.1816          -0.20    0.131167
4   2015-05-31      0.2326          -0.10    0.131167
..         ...         ...            ...         ...
115 2024-08-31     -0.0153           0.57    0.105750
116 2024-09-30     -0.3139           0.28    0.105750
117 2024-10-31     -0.1357          -0.09    0.105750
118 2024-11-30     -0.1445          -0.42    0.105750
119 2024-12-31     -0.0588          -0.06    0.105750

[120 rows x 4 columns]

In [32]:
working_df_clean = working_df_clean.merge(macro_factors, on="date", how="left")
print(working_df_clean.head())

        date  isin  cs_change  delta lr  change_in_10y_bond  change_in_slope  \
0 2022-11-30     0   -0.00267  0.000058            -0.00028         -0.00395
1 2022-12-31     0   -0.00102  0.000058             0.00517          0.00171
2 2023-01-31     0   -0.00020  0.000024            -0.00310         -0.00158
3 2023-02-28     0    0.00077  0.000024             0.00167         -0.00069
4 2023-03-31     0    0.00259  0.000024            -0.00229         -0.00179

   smi_return  v3x_change rating  maturity  cpi_change  unempl_change  \
0    0.027314   -0.030361   AAA       10.0      0.0040            0.1
1   -0.036456   -0.005036   AAA       10.0     -0.2283            0.1
2    0.050557    0.005429   AAA       10.0      0.6286            0.1
3   -0.016747   -0.001126   AAA       10.0      0.7838            0.0
4    0.000710   -0.016202   AAA       10.0      0.1623           -0.1

   gdp_change
0    0.260500
1    0.260500
2    0.061917
3    0.061917
4    0.061917

In [33]:
print(working_df_clean.columns)

Index(['date', 'isin', 'cs_change', 'delta lr', 'change_in_10y_bond',
       'change_in_slope', 'smi_return', 'v3x_change', 'rating', 'maturity',
       'cpi_change', 'unempl_change', 'gdp_change'],
      dtype='object')

In [34]:
# We add liquidity factor as Bid-Ask spread
liquidity = pd.read_excel("./data_files/liquidity.xlsx")

print(liquidity)

          date  CH1206367588  CH0508785711  CH1148728210  CH1191714703  \
0   2015-01-31           NaN           NaN           NaN           NaN
1   2015-02-28           NaN           NaN           NaN           NaN
2   2015-03-31           NaN           NaN           NaN           NaN
3   2015-04-30           NaN           NaN           NaN           NaN
4   2015-05-31           NaN           NaN           NaN           NaN
..         ...           ...           ...           ...           ...
115 2024-08-31        0.4126       0.61140       0.43010       0.23100
116 2024-09-30        0.4522       0.50340       0.27745       0.22100
117 2024-10-31        0.5090       0.55105       0.28630       0.22600
118 2024-11-30        0.5088       0.66050       0.18150       0.41515
119 2024-12-31        0.5870       0.40600       0.32350       0.34125

     CH0354836113  CH1194355116  CH0553331890  CH0347556901  CH0147144361  \
0             NaN           NaN           NaN           NaN       0.83020
1             NaN           NaN           NaN           NaN       0.80950
2             NaN           NaN           NaN           NaN       0.81020
3             NaN           NaN           NaN           NaN       0.79890
4             NaN           NaN           NaN           NaN       0.79080
..            ...           ...           ...           ...           ...
115      0.224700       0.23125      0.413630        0.0730       0.29275
116      0.333996       0.49460      0.405316        0.0799       0.34525
117      0.329500       0.22530      0.394755        0.0679       0.30300
118      0.303795       0.38240      0.608850        0.0551       0.26040
119      0.196800       0.35420      0.698270        0.0366       0.32075

     ...  CH0551990689  CH1101096522  CH1118223424  CH0537261932  \
0    ...           NaN           NaN           NaN           NaN
1    ...           NaN           NaN           NaN           NaN
2    ...           NaN           NaN           NaN           NaN
3    ...           NaN           NaN           NaN           NaN
4    ...           NaN           NaN           NaN           NaN
..   ...           ...           ...           ...           ...
115  ...      0.262496       0.23895        0.6175       0.91090
116  ...      0.207199       0.31230        0.4772       0.84720
117  ...      0.090900       0.32980        0.7231       1.01005
118  ...      0.156250       0.33250        0.0205       0.68900
119  ...      0.039500       0.31525        0.7215       0.97280

     CH0373476339  CH0576402165  CH0572327002  CH0435590358  CH0433761308  \
0             NaN           NaN           NaN           NaN           NaN
1             NaN           NaN           NaN           NaN           NaN
2             NaN           NaN           NaN           NaN           NaN
3             NaN           NaN           NaN           NaN           NaN
4             NaN           NaN           NaN           NaN           NaN
..            ...           ...           ...           ...           ...
115       0.41165       0.33813       0.60840       0.15330       0.14460
116       0.43900       0.45900       0.59880       0.01970       0.08580
117       0.40340       0.26200       0.73275       0.07960       0.06420
118       0.34880       0.41950       0.82700       0.04550       0.05145
119       0.47340       0.06825       0.61900       0.01875       0.04860

     CH0344583817
0             NaN
1             NaN
2             NaN
3             NaN
4             NaN
..            ...
115       0.31675
116       0.35630
117       0.32390
118       0.38250
119       0.41580

[120 rows x 530 columns]

In [35]:
liquidity_melted = liquidity.melt(id_vars="date", value_vars=liquidity[1:529], var_name="isin", value_name="liquidity")
print(liquidity_melted)

            date          isin  liquidity
0     2015-01-31  CH1206367588        NaN
1     2015-02-28  CH1206367588        NaN
2     2015-03-31  CH1206367588        NaN
3     2015-04-30  CH1206367588        NaN
4     2015-05-31  CH1206367588        NaN
...          ...           ...        ...
63475 2024-08-31  CH0344583817    0.31675
63476 2024-09-30  CH0344583817    0.35630
63477 2024-10-31  CH0344583817    0.32390
63478 2024-11-30  CH0344583817    0.38250
63479 2024-12-31  CH0344583817    0.41580

[63480 rows x 3 columns]

In [36]:
liquidity_melted_clean = liquidity_melted.dropna()

print(liquidity_melted_clean)

            date          isin  liquidity
93    2022-10-31  CH1206367588    0.22100
94    2022-11-30  CH1206367588    0.66500
95    2022-12-31  CH1206367588    0.86200
96    2023-01-31  CH1206367588    0.43200
97    2023-02-28  CH1206367588    0.42300
...          ...           ...        ...
63475 2024-08-31  CH0344583817    0.31675
63476 2024-09-30  CH0344583817    0.35630
63477 2024-10-31  CH0344583817    0.32390
63478 2024-11-30  CH0344583817    0.38250
63479 2024-12-31  CH0344583817    0.41580

[36925 rows x 3 columns]

In [37]:
liquidity_melted_clean['isin'] = pd.factorize(liquidity_melted_clean['isin'])[0]

/var/folders/dw/93tk385j54q9dmq3f082vbnm0000gn/T/ipykernel_41179/1286466688.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  liquidity_melted_clean['isin'] = pd.factorize(liquidity_melted_clean['isin'])[0]

In [38]:
working_df_clean = working_df_clean.merge(liquidity_melted_clean, on=["date","isin"], how="left")
print(working_df_clean)

            date  isin  cs_change  delta lr  change_in_10y_bond  \
0     2022-11-30     0   -0.00267  0.000058            -0.00028
1     2022-12-31     0   -0.00102  0.000058             0.00517
2     2023-01-31     0   -0.00020  0.000024            -0.00310
3     2023-02-28     0    0.00077  0.000024             0.00167
4     2023-03-31     0    0.00259  0.000024            -0.00229
...          ...   ...        ...       ...                 ...
36215 2024-08-31   528    0.00001  0.000040             0.00007
36216 2024-09-30   528    0.00016  0.000040            -0.00054
36217 2024-10-31   528   -0.00030  0.000040             0.00007
36218 2024-11-30   528   -0.00011  0.000040            -0.00177
36219 2024-12-31   528   -0.00010  0.000040             0.00075

       change_in_slope  smi_return  v3x_change rating  maturity  cpi_change  \
0             -0.00395    0.027314   -0.030361   AAA       10.0      0.0040
1              0.00171   -0.036456   -0.005036   AAA       10.0     -0.2283
2             -0.00158    0.050557    0.005429   AAA       10.0      0.6286
3             -0.00069   -0.016747   -0.001126   AAA       10.0      0.7838
4             -0.00179    0.000710   -0.016202   AAA       10.0      0.1623
...                ...         ...         ...    ...       ...         ...
36215          0.00104    0.009627    0.012917     AA      12.0     -0.0153
36216          0.00076   -0.021762   -0.001398     AA      12.0     -0.3139
36217          0.00050   -0.031382    0.035715     AA      12.0     -0.1357
36218          0.00034   -0.002438   -0.042992     AA      12.0     -0.1445
36219          0.00168   -0.013979    0.002462     AA      12.0     -0.0588

       unempl_change  gdp_change  liquidity
0               0.10    0.260500    0.66500
1               0.10    0.260500    0.86200
2               0.10    0.061917    0.43200
3               0.00    0.061917    0.42300
4              -0.10    0.061917    0.41700
...              ...         ...        ...
36215           0.57    0.105750    0.31675
36216           0.28    0.105750    0.35630
36217          -0.09    0.105750    0.32390
36218          -0.42    0.105750    0.38250
36219          -0.06    0.105750    0.41580

[36220 rows x 14 columns]

In [39]:
print(working_df_clean.head())

        date  isin  cs_change  delta lr  change_in_10y_bond  change_in_slope  \
0 2022-11-30     0   -0.00267  0.000058            -0.00028         -0.00395
1 2022-12-31     0   -0.00102  0.000058             0.00517          0.00171
2 2023-01-31     0   -0.00020  0.000024            -0.00310         -0.00158
3 2023-02-28     0    0.00077  0.000024             0.00167         -0.00069
4 2023-03-31     0    0.00259  0.000024            -0.00229         -0.00179

   smi_return  v3x_change rating  maturity  cpi_change  unempl_change  \
0    0.027314   -0.030361   AAA       10.0      0.0040            0.1
1   -0.036456   -0.005036   AAA       10.0     -0.2283            0.1
2    0.050557    0.005429   AAA       10.0      0.6286            0.1
3   -0.016747   -0.001126   AAA       10.0      0.7838            0.0
4    0.000710   -0.016202   AAA       10.0      0.1623           -0.1

   gdp_change  liquidity
0    0.260500      0.665
1    0.260500      0.862
2    0.061917      0.432
3    0.061917      0.423
4    0.061917      0.417

In [40]:
working_df_clean['rating'] = working_df_clean['rating'].str.strip()

In [41]:
rating_map = {
    'AAA': 1, 'AA+': 2, 'AA': 3, 'AA-': 4,
    'A+': 5, 'A': 6, 'A-': 7,
    'BBB+': 8, 'BBB': 9, 'BBB-': 10,
    'BB+': 11, 'BB': 12, 'BB-': 13,
    'B-': 14, 'NR':15
}

working_df_clean['credit_rating_numeric'] = working_df_clean['rating'].map(rating_map)

In [42]:
def rating_class(x):
    if x == 1:
        return 'AAA class bonds'
    elif x <= 4:
        return 'AA class bonds'
    elif x <= 7:
        return 'A class bonds'
    elif x <= 14:
        return 'BBB/BB/B bonds'
    else:
        return 'Not rated bonds'

In [43]:
working_df_clean['rating_class'] = working_df_clean['credit_rating_numeric'].apply(rating_class)

In [44]:
working_df_clean.isna().sum()

date                     0
isin                     0
cs_change                0
delta lr                 0
change_in_10y_bond       0
change_in_slope          0
smi_return               0
v3x_change               0
rating                   0
maturity                 0
cpi_change               0
unempl_change            0
gdp_change               0
liquidity                0
credit_rating_numeric    0
rating_class             0
dtype: int64

In [45]:
def maturity_bucket(x):
    if x <= 4:
        return 'Short-Term'
    elif x <= 10:
        return 'Medium-Term'
    else:
        return 'Long-Term'

working_df_clean['maturity_bucket'] = working_df_clean['maturity'].apply(maturity_bucket)

In [46]:
print(working_df_clean.head())

        date  isin  cs_change  delta lr  change_in_10y_bond  change_in_slope  \
0 2022-11-30     0   -0.00267  0.000058            -0.00028         -0.00395
1 2022-12-31     0   -0.00102  0.000058             0.00517          0.00171
2 2023-01-31     0   -0.00020  0.000024            -0.00310         -0.00158
3 2023-02-28     0    0.00077  0.000024             0.00167         -0.00069
4 2023-03-31     0    0.00259  0.000024            -0.00229         -0.00179

   smi_return  v3x_change rating  maturity  cpi_change  unempl_change  \
0    0.027314   -0.030361    AAA      10.0      0.0040            0.1
1   -0.036456   -0.005036    AAA      10.0     -0.2283            0.1
2    0.050557    0.005429    AAA      10.0      0.6286            0.1
3   -0.016747   -0.001126    AAA      10.0      0.7838            0.0
4    0.000710   -0.016202    AAA      10.0      0.1623           -0.1

   gdp_change  liquidity  credit_rating_numeric     rating_class  \
0    0.260500      0.665                      1  AAA class bonds
1    0.260500      0.862                      1  AAA class bonds
2    0.061917      0.432                      1  AAA class bonds
3    0.061917      0.423                      1  AAA class bonds
4    0.061917      0.417                      1  AAA class bonds

  maturity_bucket
0     Medium-Term
1     Medium-Term
2     Medium-Term
3     Medium-Term
4     Medium-Term

## Panel data

In [47]:
#Convert date column into a date value
working_df_clean['date'] = pd.to_datetime(working_df_clean['date'])

In [48]:
print(working_df_clean.head())

        date  isin  cs_change  delta lr  change_in_10y_bond  change_in_slope  \
0 2022-11-30     0   -0.00267  0.000058            -0.00028         -0.00395
1 2022-12-31     0   -0.00102  0.000058             0.00517          0.00171
2 2023-01-31     0   -0.00020  0.000024            -0.00310         -0.00158
3 2023-02-28     0    0.00077  0.000024             0.00167         -0.00069
4 2023-03-31     0    0.00259  0.000024            -0.00229         -0.00179

   smi_return  v3x_change rating  maturity  cpi_change  unempl_change  \
0    0.027314   -0.030361    AAA      10.0      0.0040            0.1
1   -0.036456   -0.005036    AAA      10.0     -0.2283            0.1
2    0.050557    0.005429    AAA      10.0      0.6286            0.1
3   -0.016747   -0.001126    AAA      10.0      0.7838            0.0
4    0.000710   -0.016202    AAA      10.0      0.1623           -0.1

   gdp_change  liquidity  credit_rating_numeric     rating_class  \
0    0.260500      0.665                      1  AAA class bonds
1    0.260500      0.862                      1  AAA class bonds
2    0.061917      0.432                      1  AAA class bonds
3    0.061917      0.423                      1  AAA class bonds
4    0.061917      0.417                      1  AAA class bonds

  maturity_bucket
0     Medium-Term
1     Medium-Term
2     Medium-Term
3     Medium-Term
4     Medium-Term

In [49]:
#we make isins unique
working_df_clean['isin'] = pd.factorize(working_df_clean['isin'])[0]

In [50]:
working_df_clean_panel = working_df_clean.set_index(['date', 'isin']).sort_index()

In [51]:
print(working_df_clean['date'].dtype)
print(working_df_clean['isin'].dtype)

datetime64[ns]
int64

In [52]:
print(working_df_clean_panel.head())

                 cs_change  delta lr  change_in_10y_bond  change_in_slope  \
date       isin
2015-01-31 8      -0.00063  0.000000            -0.00395          0.00006
           16      0.00008  0.001782            -0.00395          0.00006
           19     -0.00046  0.000000            -0.00395          0.00006
           25     -0.00077  0.000209            -0.00395          0.00006
           31     -0.00078  0.000000            -0.00395          0.00006

                 smi_return  v3x_change rating   maturity  cpi_change  \
date       isin
2015-01-31 8      -0.068915    0.045699    AAA   8.000000     -0.4006
           16     -0.068915    0.045699     NR  10.000000     -0.4006
           19     -0.068915    0.045699     NR   8.000000     -0.4006
           25     -0.068915    0.045699     A-   6.833333     -0.4006
           31     -0.068915    0.045699     AA  10.000000     -0.4006

                 unempl_change  gdp_change  liquidity  credit_rating_numeric  \
date       isin
2015-01-31 8               0.3    0.131167     0.8302                      1
           16              0.3    0.131167     0.6042                     15
           19              0.3    0.131167     1.5405                     15
           25              0.3    0.131167     0.9983                      7
           31              0.3    0.131167     1.0000                      3

                    rating_class maturity_bucket
date       isin
2015-01-31 8     AAA class bonds     Medium-Term
           16    Not rated bonds     Medium-Term
           19    Not rated bonds     Medium-Term
           25      A class bonds     Medium-Term
           31     AA class bonds     Medium-Term

In [53]:
working_df_clean_panel.to_csv("panel_data.csv")

In [54]:
working_df_clean.to_csv("working_sample_1.csv")